using static Learnix.Infrastructure.Services.HostedServices.Seeders.CourseSeeders.SeedHelpers;

namespace Learnix.Infrastructure.Services.HostedServices.Seeders.CourseSeeders;

internal static class React19Seeder
{
    public static SeedCourseDefinition GetDefinition() => new(
        "web-development",
        "React 19 with TypeScript",
        "Build modern, type-safe web UIs with React 19, hooks, TanStack Query, and Zustand. Covers component patterns, state management, and API integration.",
        19.99m,
        ["react", "typescript", "frontend", "tanstack-query"],
        [
            new("React & TypeScript Setup",
            [
                new SeedVideo("Scaffolding a React + TypeScript Project",
                    "We scaffold a Vite project with the react-ts template, configure path aliases, add Tailwind CSS, and wire up ESLint and Prettier."),
                new SeedPost("Why React with TypeScript?",
                    "TypeScript catches entire classes of runtime errors at compile time: mistyped prop names, missing required props, and incorrect return types. React 19's improved compiler makes re-render optimisation largely automatic, so type safety is the biggest remaining reason to be explicit — and TypeScript handles that."),
            ]),
            new("Components and Hooks",
            [
                new SeedVideo("Functional Components and JSX",
                    "We build a Card component from scratch, type its props interface, and explore how JSX is sugar over React.createElement — and why that matters for understanding rendering."),
                new SeedPost("useState and useEffect",
                    "`useState` manages local component state. `useEffect` synchronises with external systems. The dependency array controls re-execution. The golden rule: never put server data in `useState` — use TanStack Query instead to avoid stale data and double-fetching."),
                new SeedPost("Props and Component Composition",
                    "Props flow down; events flow up. Prefer composition (the `children` prop, named slot props) over deep prop drilling. Context is for slow-changing cross-cutting values (theme, locale, auth user) — not for frequently updating server data."),
                new SeedPost("Custom Hooks",
                    "Extract stateful logic into custom hooks (`useWindowSize`, `useDebounce`). A custom hook is any function whose name starts with `use` and that calls at least one built-in hook. Co-locate hook files with the feature they serve, not in a global `/hooks` folder."),
            ]),
            new("State and Data Fetching",
            [
                new SeedVideo("Server State with TanStack Query",
                    "A live session fetching a paginated list with `useQuery`, handling loading and error states, and invalidating the cache after a mutation — all without a single `useState` for server data."),
                new SeedPost("Fetching Data with useQuery",
                    "`useQuery({ queryKey: ['courses'], queryFn: fetchCourses })` fetches, caches, and keeps server state fresh. The `queryKey` is a stable cache identifier — include all variables the query depends on. `isLoading`, `isError`, and `data` give you everything needed to render the three UI states."),
                new SeedPost("Mutations with useMutation",
                    "`useMutation` sends writes (POST, PUT, DELETE) and hooks into loading/error/success lifecycle. Call `queryClient.invalidateQueries` in `onSuccess` to trigger a refetch. Optimistic updates via `onMutate` / `onError` rollback provide instant UI feedback."),
                new SeedVideo("Client State with Zustand",
                    "We build a theme store and an auth store using Zustand's `create<T>()` API, use selectors to minimise re-renders, and see how Zustand avoids Redux boilerplate while remaining fully typed."),
            ]),
            new("Advanced React Patterns",
            [
                new SeedVideo("Performance Optimisation",
                    "We profile a slow list render in React DevTools Profiler, apply `React.memo`, `useMemo`, and `useCallback` surgically, then let the React 19 Compiler handle the rest automatically."),
                new SeedPost("useMemo and useCallback",
                    "`useMemo` memoises an expensive computed value; `useCallback` memoises a function reference. Both are only useful when the memoised value is passed to a `React.memo`-wrapped child or used as a `useEffect` dependency. Profile first — premature memoisation adds cost without benefit."),
                new SeedPost("React 19 New Features",
                    "React 19 ships the React Compiler (auto-memoisation), the `use()` hook for suspense-based data reading, Actions for async form handling, and improved server component support. In many codebases the compiler eliminates the need for manual `useMemo`/`useCallback` entirely."),
            ]),
            new("React Assessments",
            [
                new SeedTest("Quick Check: Hooks Basics",
                    [
                        SC("Which hook manages local component state in React?",
                            "useState", "useRef", "useMemo", "useReducer"),
                        SC("What file extension is standard for TypeScript React components?",
                            ".tsx", ".ts", ".jsx", ".js"),
                        SC("What is the purpose of the dependency array in useEffect?",
                            "Controls when the effect re-runs",
                            "Declares imported modules",
                            "Lists component props",
                            "Defines state variables"),
                    ],
                    PassingThreshold: 60,
                    AttemptLimit: null),

                new SeedTest("Concept Quiz: State Management",
                    [
                        MC("Which hooks are intended for synchronising side effects?",
                            ["useEffect", "useLayoutEffect"],
                            ["useState", "useMemo", "useCallback"]),
                        MC("Which are valid React hook rules?",
                            ["Only call at the top level of a function component",
                             "Only call inside React function components or custom hooks"],
                            ["Can be called inside loops",
                             "Can be called inside conditionals",
                             "Can be called in class components"]),
                        MC("Which libraries manage client-side state well in React apps?",
                            ["Zustand", "Jotai", "Recoil"],
                            ["TanStack Query", "React Router", "Axios"]),
                    ],
                    PassingThreshold: 70,
                    AttemptLimit: 3,
                    CooldownMinutes: 2),

                new SeedTest("Comprehensive Exam",
                    [
                        SC("What is the TanStack Query `queryKey` used for?",
                            "Identifying and sharing the cached result",
                            "Specifying the API base URL",
                            "Declaring query dependencies in package.json",
                            "Setting the HTTP request timeout"),
                        MC("Which strategies prevent unnecessary re-renders in React?",
                            ["React.memo on pure components",
                             "Stable query keys in TanStack Query",
                             "Selecting minimal slices from Zustand stores"],
                            ["Storing all state in a single useState",
                             "Using class components"]),
                        TI("What Zustand function creates a typed store?", "create"),
                    ],
                    Description: "Covers TanStack Query caching, render optimisation, and Zustand store creation.",
                    PassingThreshold: 80,
                    AttemptLimit: 2,
                    CooldownMinutes: 3),

                new SeedTest("Terminology Test",
                    [
                        TI("What hook reads a context value inside a function component?", "useContext"),
                        TI("What prop name passes child elements into a parent component?", "children"),
                        TI("What React function wraps a component to skip re-renders when props are unchanged?",
                            "memo"),
                    ],
                    PassingThreshold: 50,
                    AttemptLimit: 1),

                new SeedTest("Mastery Challenge",
                    [
                        SC("What does the `key` prop help React do during list reconciliation?",
                            "Identify list items to minimise DOM mutations",
                            "Apply CSS class names",
                            "Register event listeners",
                            "Define component display names"),
                        SC("Which TanStack Query hook is used for write operations?",
                            "useMutation", "useQuery", "useInfiniteQuery", "useQueryClient"),
                        MC("Which are anti-patterns in React development?",
                            ["Storing server data in useState",
                             "Deep prop drilling across many levels",
                             "Creating new object references in render without useMemo"],
                            ["Using TanStack Query for server state",
                             "Co-locating components with their feature"]),
                        TI("What React 19 feature auto-memoises components without manual useMemo?",
                            "compiler", ignoreCase: true),
                    ],
                    PassingThreshold: 100,
                    AttemptLimit: 5,
                    CooldownMinutes: 1),
            ]),
        ],
        "react_thumbnail.png");
}
