namespace Learnix.Application.Uploads.Constants;

public static class UploadMessages
{
    public static string OnlyInstructorsUploadVideos => "Only instructors can upload videos";
    public static string OnlyInstructorsUploadCovers => "Only instructors can upload course covers";
    public static string CertificatesGeneratedBySystem => "Certificates are generated by the system";
    public static string OnlyAdminsUploadCategoryImages => "Only admins can upload category images";
}
