export const LESSON_LIMITS = {
    TITLE_MAX: 300,
    DESCRIPTION_MAX: 2000,
    POST_CONTENT_MAX: 50000,
    PASSING_THRESHOLD_MIN: 1,
    PASSING_THRESHOLD_MAX: 100,
    ATTEMPT_LIMIT_MIN: 1,
    COOLDOWN_MINUTES_MIN: 1,
    QUESTION_OPTIONS_MIN: 2,
    QUESTION_OPTIONS_MAX: 6,
} as const;
